/**
 * Root Layout Component
 * 
 * This is the root layout component that wraps all pages in the application.
 * It defines the global HTML structure, metadata, and font configuration.
 * This layout is applied to all pages and cannot be disabled.
 */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

/**
 * Font Configuration
 * 
 * Using Google Fonts Inter for consistent typography across the application.
 * The 'latin' subset includes basic Latin characters for optimal performance.
 * The font is preloaded and optimized by Next.js for better performance.
 */
const inter = Inter({ 
  subsets: ['latin'] // Load only Latin character subset to reduce font file size
});

/**
 * Metadata Configuration
 * 
 * Defines the default metadata for the application that is used by:
 * - Search engines (SEO)
 * - Social media platforms when sharing
 * - Browser tabs and bookmarks
 * 
 * This metadata can be overridden in individual page components.
 */
export const metadata: Metadata = {
  title: 'Social Media Scheduler - Social Valet',
  description: 'Schedule and manage your social media posts efficiently with our intuitive scheduling tool. Create, organize, and plan your content strategy with ease.',
};

/**
 * RootLayout Component
 * 
 * The root layout component that wraps all child pages.
 * This component is required in Next.js 13+ App Router and serves as:
 * - The HTML document structure
 * - The global font application
 * - The container for global styles
 * 
 * @param children - React nodes that represent the page content
 * @returns The complete HTML document structure with applied global styles
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // HTML document with language attribute for accessibility and SEO
    <html lang="en">
      {/**
       * Body element with Inter font class applied
       * The font class is automatically generated by Next.js and provides:
       * - CSS variables for font family
       * - Proper font loading and fallbacks
       * - Consistent typography across all components
       */}
      <body className={inter.className}>
        {/**
         * Page Content
         * 
         * This is where the actual page content gets rendered.
         * Each page component in the app directory will be injected here.
         * The layout wraps all pages, providing consistent structure and styling.
         */}
        {children}
      </body>
    </html>
  );
}